### PR TITLE
change Jahia version to 7.1.0.1 and change JahiaUser to JCRUserNode

### PR DESCRIPTION
**Pull request by Alexandre-Gadiou**
Make the plugin Jahia 7.1.0.1 compliant

### CODE REVIEW

**Comment by shyrkov** [comment]
Thank you Alexandre! There has been an internal ticket raised to track this issue and the pull request.

**Comment by jkevan** [comment]
This modification have been apply by an other PR, 
thanks for the contribution

**Comment by ghost** [comment]
@jkevan, @rvt's PRs has been closed but I don't see the fix.

**Comment by jkevan** [comment]
Hi @f4bien , here is the commit: https://github.com/Jahia/formbuilder/commit/a5a0bf0cd2dd3510169614c9b9af21be30912ec5 that have been merged on master branch

Pom have been updated to used 7.1.0.0 as parent, in a next commit: https://github.com/Jahia/formbuilder/commit/4f21c96edeb6dbea8f87c7195029a2e1e00e795b

**Comment by ghost** [comment]
My bad, I had to be on v2 branch. Thank you.

**Pull request closed without merging**
